# Generated by Django 6.0.5 on 2026-06-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ZTP Sneakers', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store/')),
                ('whatsapp_number', models.CharField(blank=True, help_text='Format: 62812xxx', max_length=20, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('crisp_website_id', models.CharField(blank=True, help_text='ID Token dari Crisp Chat', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Pengaturan Toko',
                'verbose_name_plural': 'Pengaturan Toko',
            },
        ),
    ]
