# Generated by Django 6.0.5 on 2026-06-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_storesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesetting',
            name='address',
            field=models.TextField(default='Jalan KH. Abdurahman Wahid Gg. Murbach, Kec Sungai Raya, Kabupaten Kubu Raya', help_text='Alamat lengkap toko'),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='branches_count',
            field=models.IntegerField(default=1, help_text='Jumlah cabang offline'),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='customers_count_label',
            field=models.CharField(default='1000+', help_text='Label jumlah pelanggan (e.g. 1000+)', max_length=50),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='established_year',
            field=models.IntegerField(default=2022, help_text='Tahun berdiri toko'),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='short_description',
            field=models.TextField(default='Toko Sepatu Sneakers Indonesia — Original & 100% Authentic', help_text='Deskripsi singkat untuk Hero Stats/Footer'),
        ),
    ]
