# Generated by Django 6.0.5 on 2026-06-04 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_storesetting_address_storesetting_branches_count_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoreSetting',
        ),
    ]
