# Generated by Django 6.0.5 on 2026-06-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_warrantyclaim'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrantyclaim',
            name='kategori',
            field=models.CharField(choices=[('cacat_produk', 'Cacat Produk'), ('salah_ukuran', 'Salah Ukuran / Barang Berbeda'), ('tidak_sesuai_foto', 'Tidak Sesuai Foto'), ('lainnya', 'Lainnya')], default='lainnya', max_length=50),
        ),
    ]
