# Generated by Django 6.0.5 on 2026-07-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_voucher_is_used_voucher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='max_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Batas maksimum diskon (0 = tanpa batas)', max_digits=12),
        ),
    ]
