# Generated by Django 6.0.5 on 2026-06-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('black', 'Hitam'), ('white', 'Putih'), ('red', 'Merah'), ('blue', 'Biru'), ('green', 'Hijau'), ('yellow', 'Kuning'), ('grey', 'Abu-abu'), ('brown', 'Cokelat'), ('multi', 'Multi-Warna')], default='multi', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='color_secondary',
            field=models.CharField(blank=True, choices=[('black', 'Hitam'), ('white', 'Putih'), ('red', 'Merah'), ('blue', 'Biru'), ('green', 'Hijau'), ('yellow', 'Kuning'), ('grey', 'Abu-abu'), ('brown', 'Cokelat'), ('multi', 'Multi-Warna')], help_text='Warna sekunder (Opsional)', max_length=20, null=True),
        ),
    ]
