# Generated by Django 6.0.5 on 2026-06-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_color_product_color_secondary'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/'),
        ),
        migrations.AddField(
            model_name='review',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
